"""Generate valid Emacs Lisp from CaptureTemplate instances.

Produces two kinds of output:

- ``org-roam-capture-templates`` entries for :attr:`TemplateType.ROAM_CAPTURE`
  templates — sexp tuples appended to a ``setq`` form.
- ``org-capture-templates`` entries for :attr:`TemplateType.ORG_CAPTURE`
  templates — individual ``add-to-list`` forms using the Engineering Hub
  ``eh/ensure-overnight-heading`` pattern.
"""

from __future__ import annotations

import textwrap
from datetime import datetime

from engineering_hub.capture.models import (
    CaptureTemplate,
    HeadingSpec,
    TemplateType,
)


def _escape_elisp_string(s: str) -> str:
    """Escape a Python string for use inside an elisp double-quoted string."""
    return s.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")


def _heading_to_org_lines(heading: HeadingSpec) -> list[str]:
    stars = "*" * heading.level
    lines = [f"{stars} {heading.title}"]
    if heading.body:
        lines.append("")
        lines.append(heading.body)
    for child in heading.children:
        lines.append("")
        lines.extend(_heading_to_org_lines(child))
    return lines


def _build_header_string(tpl: CaptureTemplate) -> str:
    """Build the ``#+title: ...\\n#+filetags: ...\\n* Heading`` header for file+head."""
    parts: list[str] = [f"#+title: {tpl.title_pattern}"]

    if tpl.filetags:
        inner = ":".join(tpl.filetags)
        parts.append(f"#+filetags: :{inner}:")

    parts.append("")

    for heading in tpl.headings:
        parts.extend(_heading_to_org_lines(heading))
        parts.append("")

    return "\\n".join(parts)


def _build_body_string(tpl: CaptureTemplate) -> str:
    """Build the template body — complex bodies use raw_body, simple ones use ``%?``."""
    if tpl.raw_body:
        return _escape_elisp_string(tpl.raw_body)
    return "%?"


def _build_target_path(tpl: CaptureTemplate) -> str:
    """Build the target file path from dir + filename pattern."""
    path = tpl.target_dir.rstrip("/")
    if path:
        return f"{path}/{tpl.filename_pattern}"
    return tpl.filename_pattern


def generate_roam_template_sexp(tpl: CaptureTemplate) -> str:
    """Generate a single org-roam-capture-templates entry sexp."""
    key = _escape_elisp_string(tpl.key)
    desc = _escape_elisp_string(tpl.display_name)
    body = _build_body_string(tpl)
    target_path = _escape_elisp_string(_build_target_path(tpl))
    header = _build_header_string(tpl)

    props = ""
    if tpl.properties:
        prop_lines: list[str] = []
        for k, v in tpl.properties.items():
            prop_lines.append(f":{k}: {v}")
        props_block = "\\n".join([":PROPERTIES:"] + prop_lines + [":END:"])
        header = props_block + "\\n" + header

    lines = [
        f'        ("{key}" "{desc}" plain',
        f'         "{body}"',
        f'         :target (file+head "{target_path}"',
        f'                            "{header}")',
        f"         :unnarrowed t)",
    ]
    return "\n".join(lines)


def generate_org_capture_sexp(tpl: CaptureTemplate) -> str:
    """Generate an ``add-to-list`` form for an org-capture-templates entry.

    Uses the Engineering Hub ``eh/ensure-overnight-heading`` pattern for
    agent dispatch templates.
    """
    key = _escape_elisp_string(tpl.key)
    desc = _escape_elisp_string(tpl.display_name)
    body = _build_body_string(tpl)

    if not body.startswith("- [ ] @"):
        body = f"- [ ] @{body}" if not body.startswith("-") else body

    return textwrap.dedent(f"""\
  (add-to-list 'org-capture-templates
    `("{key}" "{desc}" plain
      (file+function
       ,(lambda () (eh/daily-journal-file))
       eh/ensure-overnight-heading)
      "{body}"
      :empty-lines 0
      :immediate-finish nil)
    t)""")


def generate_elisp(templates: list[CaptureTemplate]) -> str:
    """Generate a complete elisp block from a list of CaptureTemplate instances.

    Returns a string suitable for pasting into ``$DOOMDIR/config.el``.
    """
    now = datetime.now().strftime("%Y-%m-%d %H:%M")

    roam_templates = [t for t in templates if t.template_type == TemplateType.ROAM_CAPTURE]
    org_templates = [t for t in templates if t.template_type == TemplateType.ORG_CAPTURE]

    parts: list[str] = [
        f";; Generated by engineering-hub capture export — {now}",
        ";; Copy the sections you need into your $DOOMDIR/config.el.",
        "",
    ]

    if roam_templates:
        parts.append(";; ── org-roam-capture-templates (append to your existing setq) ──")
        parts.append("")
        for tpl in roam_templates:
            parts.append(f"        ;; {tpl.display_name}")
            parts.append(generate_roam_template_sexp(tpl))
            parts.append("")

    if org_templates:
        parts.append(";; ── org-capture-templates (agent dispatch, add inside `(after! org ...)`) ──")
        parts.append("")
        for tpl in org_templates:
            parts.append(f"  ;; {tpl.display_name}")
            parts.append(generate_org_capture_sexp(tpl))
            parts.append("")

    return "\n".join(parts)
